.TH "sources/AlarmLCDBoard.h" 3 "Sat Jan 5 2019" "Version 1.0.2" "WheelMonitor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/AlarmLCDBoard.h
.SH SYNOPSIS
.br
.PP
\fC#include 'ui_AlarmLCDBoard\&.h'\fP
.br
\fC#include <QFrame>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAlarmLCDBoard\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for WheelMonitor from the source code\&.
