.TH "sources/AlarmManager.h" 3 "Sat Jan 5 2019" "Version 1.0.2" "WheelMonitor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/AlarmManager.h \- 管理所有的报警  

.SH SYNOPSIS
.br
.PP
\fC#include 'AlarmEvent\&.h'\fP
.br
\fC#include 'Plc\&.h'\fP
.br
\fC#include 'imageprocess\&.h'\fP
.br
\fC#include 'mainwindow\&.h'\fP
.br
\fC#include 'playbackwidget\&.h'\fP
.br
\fC#include <QObject>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAlarmManager\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
管理所有的报警 


.PP
\fBDate:\fP
.RS 4
2018/11/26 3:00
.RE
.PP
\fBAuthor:\fP
.RS 4
cx3386 Contact: cx3386@163.com 
.RE
.PP
\fBCopyright(c):\fP
.RS 4
cx3386\&. All Rights Reserved TODO: long description
.RE
.PP
\fBNote:\fP
.RS 4
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP

.PP
Definition in file \fBAlarmManager\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for WheelMonitor from the source code\&.
