.TH "sources/backuplogdialog.cpp" 3 "Sat Jan 5 2019" "Version 1.0.2" "WheelMonitor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/backuplogdialog.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'stdafx\&.h'\fP
.br
\fC#include 'backuplogdialog\&.h'\fP
.br
\fC#include 'common\&.h'\fP
.br
\fC#include 'quazip\&.h'\fP
.br
\fC#include 'quazipfile\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for WheelMonitor from the source code\&.
