.TH "BackupLogDialog" 3 "Sat Jan 5 2019" "Version 1.0.2" "WheelMonitor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BackupLogDialog
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <backuplogdialog\&.h>\fP
.PP
Inherits QDialog\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBackupLogDialog\fP (QWidget *parent=nullptr)"
.br
.ti -1c
.RI "\fB~BackupLogDialog\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 18 of file backuplogdialog\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "BackupLogDialog::BackupLogDialog (QWidget * parent = \fCnullptr\fP)\fC [explicit]\fP"
UI 
.PP
Definition at line 8 of file backuplogdialog\&.cpp\&.
.SS "BackupLogDialog::~BackupLogDialog ()"

.PP
Definition at line 164 of file backuplogdialog\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for WheelMonitor from the source code\&.
