.TH "BackupInfo" 3 "Sat Jan 5 2019" "Version 1.0.2" "WheelMonitor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BackupInfo
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <backuplogdialog\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QString \fBpath\fP"
.br
.ti -1c
.RI "bool \fBisSelected\fP"
.br
.ti -1c
.RI "bool \fBisAll\fP"
.br
.ti -1c
.RI "int \fBday\fP"
.br
.ti -1c
.RI "int \fBmax_day\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file backuplogdialog\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "int BackupInfo::day"

.PP
Definition at line 11 of file backuplogdialog\&.h\&.
.SS "bool BackupInfo::isAll"

.PP
Definition at line 10 of file backuplogdialog\&.h\&.
.SS "bool BackupInfo::isSelected"

.PP
Definition at line 9 of file backuplogdialog\&.h\&.
.SS "int BackupInfo::max_day"

.PP
Definition at line 12 of file backuplogdialog\&.h\&.
.SS "QString BackupInfo::path"

.PP
Definition at line 8 of file backuplogdialog\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for WheelMonitor from the source code\&.
