.TH "CamProfile" 3 "Sat Jan 5 2019" "Version 1.0.2" "WheelMonitor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CamProfile
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <camprofile\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QString \fBcamIP\fP = '192\&.168\&.2\&.84'"
.br
.ti -1c
.RI "int \fBcamPort\fP = 8000"
.br
.ti -1c
.RI "QString \fBcamUserName\fP = 'admin'"
.br
.ti -1c
.RI "QString \fBcamPassword\fP = 'baosteel123'"
.br
.ti -1c
.RI "int \fBframeInterv\fP = 7"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file camprofile\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "QString CamProfile::camIP = '192\&.168\&.2\&.84'"

.PP
Definition at line 7 of file camprofile\&.h\&.
.SS "QString CamProfile::camPassword = 'baosteel123'"

.PP
Definition at line 10 of file camprofile\&.h\&.
.SS "int CamProfile::camPort = 8000"

.PP
Definition at line 8 of file camprofile\&.h\&.
.SS "QString CamProfile::camUserName = 'admin'"

.PP
Definition at line 9 of file camprofile\&.h\&.
.SS "int CamProfile::frameInterv = 7"

.PP
Definition at line 11 of file camprofile\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for WheelMonitor from the source code\&.
