.TH "sources/camprofile.cpp" 3 "Sat Jan 5 2019" "Version 1.0.2" "WheelMonitor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/camprofile.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'stdafx\&.h'\fP
.br
\fC#include 'camprofile\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "QDataStream & \fBoperator<<\fP (QDataStream &out, const \fBCamProfile\fP &p)"
.br
.ti -1c
.RI "QDataStream & \fBoperator>>\fP (QDataStream &in, \fBCamProfile\fP &p)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "QDataStream& operator<< (QDataStream & out, const \fBCamProfile\fP & p)"

.PP
Definition at line 4 of file camprofile\&.cpp\&.
.SS "QDataStream& operator>> (QDataStream & in, \fBCamProfile\fP & p)"

.PP
Definition at line 10 of file camprofile\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for WheelMonitor from the source code\&.
