.TH "CharSegment" 3 "Sat Jan 5 2019" "Version 1.0.2" "WheelMonitor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CharSegment
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ocr\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCharSegment\fP (Mat i, Rect p)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Mat \fBimg\fP"
.br
.ti -1c
.RI "Rect \fBpos\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 12 of file ocr\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CharSegment::CharSegment (Mat i, Rect p)\fC [inline]\fP"

.PP
Definition at line 15 of file ocr\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "Mat CharSegment::img"

.PP
Definition at line 13 of file ocr\&.h\&.
.SS "Rect CharSegment::pos"

.PP
Definition at line 14 of file ocr\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for WheelMonitor from the source code\&.
