.TH "sources/common.h" 3 "Sat Jan 5 2019" "Version 1.0.2" "WheelMonitor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/common.h \- include the common definition\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <QString>\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "const QString \fBPRODUCT_NAME\fP = QStringLiteral('宝钢环冷机台车车轮状态监测系统')"
.br
.RI "displayname "
.ti -1c
.RI "const char \fBCOPYRIGHT\fP [] = 'Copyright(C) 2018 ZJU\&. All Rights Reserved'"
.br
.ti -1c
.RI "const char \fBAUTHOR\fP [] = 'cx3386@163\&.com'"
.br
.ti -1c
.RI "QString \fBappDirPath\fP"
.br
.RI "the directory contains the app\&.exe, '/'e\&.g\&. C:/QQ "
.ti -1c
.RI "QString \fBappFilePath\fP"
.br
.RI "the file path of app\&.exe, '/'e\&.g\&. C:/QQ/qq\&.exe "
.ti -1c
.RI "QString \fBcaptureDirPath\fP"
.br
.RI "capture dir "
.ti -1c
.RI "QString \fBconfigDirPath\fP"
.br
.RI "config dir "
.ti -1c
.RI "QString \fBvideoDirPath\fP"
.br
.RI "video dir "
.ti -1c
.RI "QString \fBcacheDirPath\fP"
.br
.RI "cache dir "
.ti -1c
.RI "QString \fBmatchDirPath\fP"
.br
.RI "match dir "
.ti -1c
.RI "QString \fBlogDirPath\fP"
.br
.RI "log dir "
.ti -1c
.RI "QString \fBocrPatternDirPath\fP"
.br
.RI "ocr sample dir "
.ti -1c
.RI "QString \fBocrDirPath\fP"
.br
.RI "ocr dir "
.ti -1c
.RI "QString \fBdatabaseFilePath\fP"
.br
.RI "database file path "
.ti -1c
.RI "const char \fBBACKUP_ZIP_NAME\fP [] = 'WheelMonitor Bak\&.zip'"
.br
.in -1c
.SH "Detailed Description"
.PP 
include the common definition\&. 


.PP
\fBAuthor:\fP
.RS 4
cx3386 
.RE
.PP
\fBDate:\fP
.RS 4
2018/01/24
.RE
.PP
.IP "\(bu" 2
detailed information about this application, used in windows property dialog\&.
.IP "\(bu" 2
global application, file or folder path, or name\&.
.IP "\(bu" 2
global database connection name(threads should NOT share connections to database)\&.
.IP "\(bu" 2
global enums\&.
.IP "\(bu" 2
other sundry\&. 
.PP

.PP
Definition in file \fBcommon\&.h\fP\&.
.SH "Variable Documentation"
.PP 
.SS "QString appDirPath"

.PP
the directory contains the app\&.exe, '/'e\&.g\&. C:/QQ 
.PP
Definition at line 14 of file main\&.cpp\&.
.SS "QString appFilePath"

.PP
the file path of app\&.exe, '/'e\&.g\&. C:/QQ/qq\&.exe 
.PP
Definition at line 15 of file main\&.cpp\&.
.SS "const char AUTHOR[] = 'cx3386@163\&.com'"

.PP
Definition at line 25 of file common\&.h\&.
.SS "const char BACKUP_ZIP_NAME[] = 'WheelMonitor Bak\&.zip'"

.PP
Definition at line 45 of file common\&.h\&.
.SS "QString cacheDirPath"

.PP
cache dir 
.PP
Definition at line 19 of file main\&.cpp\&.
.SS "QString captureDirPath"

.PP
capture dir 
.PP
Definition at line 16 of file main\&.cpp\&.
.SS "QString configDirPath"

.PP
config dir 
.PP
Definition at line 17 of file main\&.cpp\&.
.SS "const char COPYRIGHT[] = 'Copyright(C) 2018 ZJU\&. All Rights Reserved'"

.PP
Definition at line 24 of file common\&.h\&.
.SS "QString databaseFilePath"

.PP
database file path 
.PP
Definition at line 25 of file main\&.cpp\&.
.SS "QString logDirPath"

.PP
log dir 
.PP
Definition at line 22 of file main\&.cpp\&.
.SS "QString matchDirPath"

.PP
match dir 
.PP
Definition at line 20 of file main\&.cpp\&.
.SS "QString ocrDirPath"

.PP
ocr dir 
.PP
Definition at line 24 of file main\&.cpp\&.
.SS "QString ocrPatternDirPath"

.PP
ocr sample dir 
.PP
Definition at line 23 of file main\&.cpp\&.
.SS "const QString PRODUCT_NAME = QStringLiteral('宝钢环冷机台车车轮状态监测系统')"

.PP
displayname 
.PP
Definition at line 22 of file common\&.h\&.
.SS "QString videoDirPath"

.PP
video dir 
.PP
Definition at line 18 of file main\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for WheelMonitor from the source code\&.
