.TH "sources/confighelper.h" 3 "Sat Jan 5 2019" "Version 1.0.2" "WheelMonitor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/confighelper.h
.SH SYNOPSIS
.br
.PP
\fC#include 'camprofile\&.h'\fP
.br
\fC#include 'improfile\&.h'\fP
.br
\fC#include 'ocrprofile\&.h'\fP
.br
\fC#include <QObject>\fP
.br
\fC#include <QSettings>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBDevSpec\fP"
.br
.RI "device specific parameters include camera,image process, ocr process "
.ti -1c
.RI "class \fBConfigHelper\fP"
.br
.RI "用于设置文件ini的相关操作，包括读取和保存 "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for WheelMonitor from the source code\&.
