.TH "sources/confighelper.cpp" 3 "Sat Jan 5 2019" "Version 1.0.2" "WheelMonitor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/confighelper.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'stdafx\&.h'\fP
.br
\fC#include 'common\&.h'\fP
.br
\fC#include 'confighelper\&.h'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "const QString \fBGP_CAM\fP = 'IPCamera'"
.br
.ti -1c
.RI "const QString \fBGP_IM\fP = 'ImageProess'"
.br
.ti -1c
.RI "const QString \fBGP_OCR\fP = 'ocr'"
.br
.ti -1c
.RI "const QString \fBGP_COMMON\fP = 'Common'"
.br
.ti -1c
.RI "const QString \fBGP_DEV\fP = 'Device'"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const QString GP_CAM = 'IPCamera'"

.PP
Definition at line 7 of file confighelper\&.cpp\&.
.SS "const QString GP_COMMON = 'Common'"

.PP
Definition at line 10 of file confighelper\&.cpp\&.
.SS "const QString GP_DEV = 'Device'"

.PP
Definition at line 11 of file confighelper\&.cpp\&.
.SS "const QString GP_IM = 'ImageProess'"

.PP
Definition at line 8 of file confighelper\&.cpp\&.
.SS "const QString GP_OCR = 'ocr'"

.PP
Definition at line 9 of file confighelper\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for WheelMonitor from the source code\&.
