.TH "DevSpec" 3 "Sat Jan 5 2019" "Version 1.0.2" "WheelMonitor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DevSpec \- device specific parameters include camera,image process, ocr process  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <confighelper\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCamProfile\fP \fBcamProfile\fP"
.br
.ti -1c
.RI "\fBImProfile\fP \fBimProfile\fP { camProfile\&.frameInterv }"
.br
.ti -1c
.RI "\fBOcrProfile\fP \fBocrProfile\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
device specific parameters include camera,image process, ocr process 


.PP
\fBAuthor:\fP
.RS 4
cx3386 
.RE
.PP
\fBDate:\fP
.RS 4
ÈýÔÂ 2018 
.RE
.PP

.PP
Definition at line 18 of file confighelper\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBCamProfile\fP DevSpec::camProfile"

.PP
Definition at line 19 of file confighelper\&.h\&.
.SS "\fBImProfile\fP DevSpec::imProfile { camProfile\&.frameInterv }"

.PP
Definition at line 20 of file confighelper\&.h\&.
.SS "\fBOcrProfile\fP DevSpec::ocrProfile"

.PP
Definition at line 21 of file confighelper\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for WheelMonitor from the source code\&.
