.TH "sources Directory Reference" 3 "Sat Jan 5 2019" "Version 1.0.2" "WheelMonitor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAlarmEvent\&.h\fP"
.br
.ti -1c
.RI "file \fBAlarmLCDBoard\&.cpp\fP"
.br
.ti -1c
.RI "file \fBAlarmLCDBoard\&.h\fP"
.br
.ti -1c
.RI "file \fBAlarmManager\&.cpp\fP"
.br
.ti -1c
.RI "file \fBAlarmManager\&.h\fP"
.br
.RI "管理所有的报警 "
.ti -1c
.RI "file \fBbackuplogdialog\&.cpp\fP"
.br
.ti -1c
.RI "file \fBbackuplogdialog\&.h\fP"
.br
.ti -1c
.RI "file \fBcamprofile\&.cpp\fP"
.br
.ti -1c
.RI "file \fBcamprofile\&.h\fP"
.br
.ti -1c
.RI "file \fBcommon\&.h\fP"
.br
.RI "include the common definition\&. "
.ti -1c
.RI "file \fBconfighelper\&.cpp\fP"
.br
.ti -1c
.RI "file \fBconfighelper\&.h\fP"
.br
.ti -1c
.RI "file \fBcustomslider\&.cpp\fP"
.br
.ti -1c
.RI "file \fBcustomslider\&.h\fP"
.br
.ti -1c
.RI "file \fBdatabase\&.h\fP"
.br
.ti -1c
.RI "file \fBHandleSensorDevice\&.cpp\fP"
.br
.ti -1c
.RI "file \fBHandleSensorDevice\&.h\fP"
.br
.ti -1c
.RI "file \fBhikvideocapture\&.cpp\fP"
.br
.ti -1c
.RI "file \fBhikvideocapture\&.h\fP"
.br
.RI "采集录像 "
.ti -1c
.RI "file \fBidentification\&.cpp\fP"
.br
.ti -1c
.RI "file \fBidentification\&.h\fP"
.br
.ti -1c
.RI "file \fBimageprocess\&.cpp\fP"
.br
.ti -1c
.RI "file \fBimageprocess\&.h\fP"
.br
.ti -1c
.RI "file \fBimprofile\&.cpp\fP"
.br
.ti -1c
.RI "file \fBimprofile\&.h\fP"
.br
.ti -1c
.RI "file \fBLevelRecorder\&.cpp\fP"
.br
.ti -1c
.RI "file \fBLevelRecorder\&.h\fP"
.br
.RI "用于记录电平的高低 "
.ti -1c
.RI "file \fBlogindialog\&.cpp\fP"
.br
.ti -1c
.RI "file \fBlogindialog\&.h\fP"
.br
.ti -1c
.RI "file \fBmain\&.cpp\fP"
.br
.ti -1c
.RI "file \fBmainwindow\&.cpp\fP"
.br
.ti -1c
.RI "file \fBmainwindow\&.h\fP"
.br
.ti -1c
.RI "file \fBMatchViewer\&.cpp\fP"
.br
.ti -1c
.RI "file \fBMatchViewer\&.h\fP"
.br
.ti -1c
.RI "file \fBmysqltablemodel\&.cpp\fP"
.br
.ti -1c
.RI "file \fBmysqltablemodel\&.h\fP"
.br
.ti -1c
.RI "file \fBocr\&.cpp\fP"
.br
.ti -1c
.RI "file \fBocr\&.h\fP"
.br
.ti -1c
.RI "file \fBocrprofile\&.cpp\fP"
.br
.ti -1c
.RI "file \fBocrprofile\&.h\fP"
.br
.ti -1c
.RI "file \fBoutlierhelper\&.cpp\fP"
.br
.ti -1c
.RI "file \fBoutlierhelper\&.h\fP"
.br
.ti -1c
.RI "file \fBplaybackwidget\&.cpp\fP"
.br
.ti -1c
.RI "file \fBplaybackwidget\&.h\fP"
.br
.ti -1c
.RI "file \fBplayer\&.cpp\fP"
.br
.ti -1c
.RI "file \fBplayer\&.h\fP"
.br
.ti -1c
.RI "file \fBPlc\&.cpp\fP"
.br
.ti -1c
.RI "file \fBPlc\&.h\fP"
.br
.ti -1c
.RI "file \fBresource\&.h\fP"
.br
.ti -1c
.RI "file \fBrobustmatcher\&.cpp\fP"
.br
.ti -1c
.RI "file \fBrobustmatcher\&.h\fP"
.br
.ti -1c
.RI "file \fBSensorDevice\&.cpp\fP"
.br
.ti -1c
.RI "file \fBSensorDevice\&.h\fP"
.br
.ti -1c
.RI "file \fBsettingdialog\&.cpp\fP"
.br
.ti -1c
.RI "file \fBsettingdialog\&.h\fP"
.br
.ti -1c
.RI "file \fBSpeedIntegrator\&.cpp\fP"
.br
.ti -1c
.RI "file \fBSpeedIntegrator\&.h\fP"
.br
.ti -1c
.RI "file \fBstdafx\&.cpp\fP"
.br
.ti -1c
.RI "file \fBstdafx\&.h\fP"
.br
.ti -1c
.RI "file \fBvideowidget\&.cpp\fP"
.br
.ti -1c
.RI "file \fBvideowidget\&.h\fP"
.br
.ti -1c
.RI "file \fBViewSensorImage\&.cpp\fP"
.br
.ti -1c
.RI "file \fBViewSensorImage\&.h\fP"
.br
.in -1c
