.TH "sources/identification.h" 3 "Sat Jan 5 2019" "Version 1.0.2" "WheelMonitor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/identification.h
.SH SYNOPSIS
.br
.PP
\fC#include <QObject>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBIdentification\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for WheelMonitor from the source code\&.
