.TH "sources/identification.cpp" 3 "Sat Jan 5 2019" "Version 1.0.2" "WheelMonitor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/identification.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'stdafx\&.h'\fP
.br
\fC#include 'identification\&.h'\fP
.br
\fC#include <QNetworkInterface>\fP
.br
\fC#include <intrin\&.h>\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "const char \fBCPU_ID\fP [] = 'BFEBFBFF506E3'"
.br
.ti -1c
.RI "const char \fBLOCAL_MAC\fP [] = '1C:1B:0D:6C:23:B1'"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const char CPU_ID[] = 'BFEBFBFF506E3'"

.PP
Definition at line 7 of file identification\&.cpp\&.
.SS "const char LOCAL_MAC[] = '1C:1B:0D:6C:23:B1'"

.PP
Definition at line 8 of file identification\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for WheelMonitor from the source code\&.
