.TH "sources/imageprocess.h" 3 "Sat Jan 5 2019" "Version 1.0.2" "WheelMonitor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/imageprocess.h
.SH SYNOPSIS
.br
.PP
\fC#include 'LevelRecorder\&.h'\fP
.br
\fC#include 'database\&.h'\fP
.br
\fC#include <QObject>\fP
.br
\fC#include <opencv2/opencv\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBImageProcess\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const int \fBIM_PROC_VALID_MIN_COUNT\fP = 10"
.br
.ti -1c
.RI "const int \fBIM_PROC_INVALID_SPEED\fP = 888"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const int IM_PROC_INVALID_SPEED = 888"

.PP
Definition at line 8 of file imageprocess\&.h\&.
.SS "const int IM_PROC_VALID_MIN_COUNT = 10"

.PP
Definition at line 7 of file imageprocess\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for WheelMonitor from the source code\&.
