.TH "sources/improfile.cpp" 3 "Sat Jan 5 2019" "Version 1.0.2" "WheelMonitor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/improfile.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'stdafx\&.h'\fP
.br
\fC#include 'improfile\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "QDataStream & \fBoperator<<\fP (QDataStream &out, const \fBImProfile\fP &p)"
.br
.ti -1c
.RI "QDataStream & \fBoperator>>\fP (QDataStream &in, \fBImProfile\fP &p)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "QDataStream& operator<< (QDataStream & out, const \fBImProfile\fP & p)"

.PP
Definition at line 4 of file improfile\&.cpp\&.
.SS "QDataStream& operator>> (QDataStream & in, \fBImProfile\fP & p)"

.PP
Definition at line 10 of file improfile\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for WheelMonitor from the source code\&.
