.TH "LoginDialog" 3 "Sat Jan 5 2019" "Version 1.0.2" "WheelMonitor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LoginDialog
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <logindialog\&.h>\fP
.PP
Inherits QDialog\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLoginDialog\fP (QWidget *parent=Q_NULLPTR)"
.br
.ti -1c
.RI "\fB~LoginDialog\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file logindialog\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "LoginDialog::LoginDialog (QWidget * parent = \fCQ_NULLPTR\fP)"

.PP
Definition at line 13 of file logindialog\&.cpp\&.
.SS "LoginDialog::~LoginDialog ()"

.PP
Definition at line 27 of file logindialog\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for WheelMonitor from the source code\&.
