.TH "sources/mainwindow.h" 3 "Sat Jan 5 2019" "Version 1.0.2" "WheelMonitor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/mainwindow.h
.SH SYNOPSIS
.br
.PP
\fC#include 'common\&.h'\fP
.br
\fC#include 'ui_mainwindow\&.h'\fP
.br
\fC#include <QtWidgets/QMainWindow>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMainWindow\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for WheelMonitor from the source code\&.
