.TH "sources/MatchViewer.h" 3 "Sat Jan 5 2019" "Version 1.0.2" "WheelMonitor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/MatchViewer.h
.SH SYNOPSIS
.br
.PP
\fC#include <QWidget>\fP
.br
\fC#include 'ui_MatchViewer\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMatchViewer\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for WheelMonitor from the source code\&.
