.TH "MatchViewer" 3 "Sat Jan 5 2019" "Version 1.0.2" "WheelMonitor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MatchViewer
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <MatchViewer\&.h>\fP
.PP
Inherits QWidget\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMatchViewer\fP (QWidget *parent=Q_NULLPTR)"
.br
.ti -1c
.RI "\fB~MatchViewer\fP ()"
.br
.ti -1c
.RI "void \fBbindDev\fP (\fBImageProcess\fP *imageProcess)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file MatchViewer\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MatchViewer::MatchViewer (QWidget * parent = \fCQ_NULLPTR\fP)"

.PP
Definition at line 6 of file MatchViewer\&.cpp\&.
.SS "MatchViewer::~MatchViewer ()"

.PP
Definition at line 12 of file MatchViewer\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void MatchViewer::bindDev (\fBImageProcess\fP * imageProcess)"

.PP
Definition at line 16 of file MatchViewer\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for WheelMonitor from the source code\&.
