.TH "sources/ocr.h" 3 "Sat Jan 5 2019" "Version 1.0.2" "WheelMonitor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/ocr.h
.SH SYNOPSIS
.br
.PP
\fC#include <QObject>\fP
.br
\fC#include <opencv\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBCharSegment\fP"
.br
.ti -1c
.RI "class \fBOCR\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const char \fBOCR_MISS\fP [] = 'MIS'"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const char OCR_MISS[] = 'MIS'"

.PP
Definition at line 7 of file ocr\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for WheelMonitor from the source code\&.
