.TH "OcrProfile" 3 "Sat Jan 5 2019" "Version 1.0.2" "WheelMonitor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OcrProfile
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ocrprofile\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBplate_x_min\fP = 100"
.br
.ti -1c
.RI "int \fBplate_x_max\fP = 250"
.br
.ti -1c
.RI "int \fBplate_y_min\fP = 90"
.br
.ti -1c
.RI "int \fBplate_y_max\fP = 200"
.br
.ti -1c
.RI "int \fBplate_width_min\fP = 160"
.br
.ti -1c
.RI "int \fBplate_width_max\fP = 190"
.br
.ti -1c
.RI "int \fBplate_height_min\fP = 110"
.br
.ti -1c
.RI "int \fBplate_height_max\fP = 130"
.br
.ti -1c
.RI "int \fBnum_width_min\fP = 20"
.br
.ti -1c
.RI "int \fBnum_width_max\fP = 50"
.br
.ti -1c
.RI "int \fBnum_height_min\fP = 50"
.br
.ti -1c
.RI "int \fBnum_height_max\fP = 75"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file ocrprofile\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "int OcrProfile::num_height_max = 75"

.PP
Definition at line 16 of file ocrprofile\&.h\&.
.SS "int OcrProfile::num_height_min = 50"

.PP
Definition at line 15 of file ocrprofile\&.h\&.
.SS "int OcrProfile::num_width_max = 50"

.PP
Definition at line 14 of file ocrprofile\&.h\&.
.SS "int OcrProfile::num_width_min = 20"

.PP
Definition at line 13 of file ocrprofile\&.h\&.
.SS "int OcrProfile::plate_height_max = 130"

.PP
Definition at line 12 of file ocrprofile\&.h\&.
.SS "int OcrProfile::plate_height_min = 110"

.PP
Definition at line 11 of file ocrprofile\&.h\&.
.SS "int OcrProfile::plate_width_max = 190"

.PP
Definition at line 10 of file ocrprofile\&.h\&.
.SS "int OcrProfile::plate_width_min = 160"

.PP
Definition at line 9 of file ocrprofile\&.h\&.
.SS "int OcrProfile::plate_x_max = 250"

.PP
Definition at line 6 of file ocrprofile\&.h\&.
.SS "int OcrProfile::plate_x_min = 100"

.PP
Definition at line 5 of file ocrprofile\&.h\&.
.SS "int OcrProfile::plate_y_max = 200"

.PP
Definition at line 8 of file ocrprofile\&.h\&.
.SS "int OcrProfile::plate_y_min = 90"

.PP
Definition at line 7 of file ocrprofile\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for WheelMonitor from the source code\&.
