.TH "sources/ocrprofile.h" 3 "Sat Jan 5 2019" "Version 1.0.2" "WheelMonitor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/ocrprofile.h
.SH SYNOPSIS
.br
.PP
\fC#include <opencv\&.hpp>\fP
.br
\fC#include <QMetaType>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBOcrProfile\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "QDataStream & \fBoperator<<\fP (QDataStream &out, const \fBOcrProfile\fP &p)"
.br
.ti -1c
.RI "QDataStream & \fBoperator>>\fP (QDataStream &in, \fBOcrProfile\fP &p)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "QDataStream& operator<< (QDataStream & out, const \fBOcrProfile\fP & p)"

.PP
Definition at line 4 of file ocrprofile\&.cpp\&.
.SS "QDataStream& operator>> (QDataStream & in, \fBOcrProfile\fP & p)"

.PP
Definition at line 10 of file ocrprofile\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for WheelMonitor from the source code\&.
