.TH "OutlierHelper" 3 "Sat Jan 5 2019" "Version 1.0.2" "WheelMonitor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OutlierHelper
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <outlierhelper\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOutlierHelper\fP ()=default"
.br
.ti -1c
.RI "\fB~OutlierHelper\fP ()=default"
.br
.ti -1c
.RI "void \fBremoveOutliers\fP (std::vector< double > &v) const"
.br
.ti -1c
.RI "double \fBmean\fP (std::vector< double > v) const"
.br
.ti -1c
.RI "double \fBstDev\fP (std::vector< double > v) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file outlierhelper\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "OutlierHelper::OutlierHelper ()\fC [default]\fP"

.SS "OutlierHelper::~OutlierHelper ()\fC [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "double OutlierHelper::mean (std::vector< double > v) const"

.PP
Definition at line 166 of file outlierhelper\&.cpp\&.
.SS "void OutlierHelper::removeOutliers (std::vector< double > & v) const"

.PP
Definition at line 109 of file outlierhelper\&.cpp\&.
.SS "double OutlierHelper::stDev (std::vector< double > v) const"

.PP
Definition at line 182 of file outlierhelper\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for WheelMonitor from the source code\&.
