.TH "sources/playbackwidget.cpp" 3 "Sat Jan 5 2019" "Version 1.0.2" "WheelMonitor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/playbackwidget.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'stdafx\&.h'\fP
.br
\fC#include 'common\&.h'\fP
.br
\fC#include 'database\&.h'\fP
.br
\fC#include 'mysqltablemodel\&.h'\fP
.br
\fC#include 'playbackwidget\&.h'\fP
.br
\fC#include 'player\&.h'\fP
.br
\fC#include <QtSql>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for WheelMonitor from the source code\&.
