.TH "sources/Plc.cpp" 3 "Sat Jan 5 2019" "Version 1.0.2" "WheelMonitor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/Plc.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'stdafx\&.h'\fP
.br
\fC#include 'AlarmEvent\&.h'\fP
.br
\fC#include 'Plc\&.h'\fP
.br
\fC#include 'SpeedIntegrator\&.h'\fP
.br
\fC#include 'common\&.h'\fP
.br
\fC#include 'confighelper\&.h'\fP
.br
\fC#include <QSerialPort>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for WheelMonitor from the source code\&.
