.TH "sources/resource.h" 3 "Sat Jan 5 2019" "Version 1.0.2" "WheelMonitor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/resource.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBIDI_ICON1\fP   102"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define IDI_ICON1   102"

.PP
Definition at line 5 of file resource\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for WheelMonitor from the source code\&.
