.TH "RobustMatcher" 3 "Sat Jan 5 2019" "Version 1.0.2" "WheelMonitor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RobustMatcher
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <robustmatcher\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRobustMatcher\fP ()"
.br
.ti -1c
.RI "\fB~RobustMatcher\fP ()"
.br
.ti -1c
.RI "bool \fBmatch\fP (cv::Mat src1, cv::Mat src2, double maskOuterRatio, double maskInnerRatio, cv::Mat &img_matches, double &angle)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file robustmatcher\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RobustMatcher::RobustMatcher ()"

.PP
Definition at line 12 of file robustmatcher\&.cpp\&.
.SS "RobustMatcher::~RobustMatcher ()"

.PP
Definition at line 16 of file robustmatcher\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "bool RobustMatcher::match (cv::Mat src1, cv::Mat src2, double maskOuterRatio, double maskInnerRatio, cv::Mat & img_matches, double & angle)"

.PP
Definition at line 24 of file robustmatcher\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for WheelMonitor from the source code\&.
