.TH "sources/robustmatcher.cpp" 3 "Sat Jan 5 2019" "Version 1.0.2" "WheelMonitor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/robustmatcher.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'stdafx\&.h'\fP
.br
\fC#include 'robustmatcher\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBM_PI\fP   (3\&.14159265358979323846)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define M_PI   (3\&.14159265358979323846)"

.PP
Definition at line 6 of file robustmatcher\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for WheelMonitor from the source code\&.
