.TH "sources/SensorDevice.h" 3 "Sat Jan 5 2019" "Version 1.0.2" "WheelMonitor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/SensorDevice.h
.SH SYNOPSIS
.br
.PP
\fC#include 'LevelRecorder\&.h'\fP
.br
\fC#include <QObject>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSensor\fP"
.br
.ti -1c
.RI "class \fBCkPt\fP"
.br
.ti -1c
.RI "class \fBSensorDevice\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for WheelMonitor from the source code\&.
