.TH "sources/settingdialog.h" 3 "Sat Jan 5 2019" "Version 1.0.2" "WheelMonitor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/settingdialog.h
.SH SYNOPSIS
.br
.PP
\fC#include 'ui_SettingDialog\&.h'\fP
.br
\fC#include <QDialog>\fP
.br
\fC#include <opencv2/opencv\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSettingDialog\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for WheelMonitor from the source code\&.
