.TH "SettingDialog" 3 "Sat Jan 5 2019" "Version 1.0.2" "WheelMonitor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SettingDialog
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <settingdialog\&.h>\fP
.PP
Inherits QDialog\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSettingDialog\fP (\fBConfigHelper\fP *ch, QWidget *parent=Q_NULLPTR)"
.br
.ti -1c
.RI "\fB~SettingDialog\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 8 of file settingdialog\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SettingDialog::SettingDialog (\fBConfigHelper\fP * ch, QWidget * parent = \fCQ_NULLPTR\fP)"

.PP
Definition at line 5 of file settingdialog\&.cpp\&.
.SS "SettingDialog::~SettingDialog ()"

.PP
Definition at line 56 of file settingdialog\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for WheelMonitor from the source code\&.
