.TH "sources/SpeedIntegrator.h" 3 "Sat Jan 5 2019" "Version 1.0.2" "WheelMonitor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/SpeedIntegrator.h
.SH SYNOPSIS
.br
.PP
\fC#include <QObject>\fP
.br
\fC#include 'Plc\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSpeedIntegrator\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
cx3386 
.RE
.PP
\fBDate:\fP
.RS 4
Ê®¶þÔÂ 2018 
.RE
.PP

.PP
Definition in file \fBSpeedIntegrator\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for WheelMonitor from the source code\&.
