.TH "VideoWidget" 3 "Sat Jan 5 2019" "Version 1.0.2" "WheelMonitor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VideoWidget
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <videowidget\&.h>\fP
.PP
Inherits QVideoWidget\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVideoWidget\fP (QWidget *parent=0)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBkeyPressEvent\fP (QKeyEvent *event) override"
.br
.ti -1c
.RI "void \fBmouseDoubleClickEvent\fP (QMouseEvent *event) override"
.br
.ti -1c
.RI "void \fBmousePressEvent\fP (QMouseEvent *event) override"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 46 of file videowidget\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "VideoWidget::VideoWidget (QWidget * parent = \fC0\fP)"

.PP
Definition at line 44 of file videowidget\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void VideoWidget::keyPressEvent (QKeyEvent * event)\fC [override]\fP, \fC [protected]\fP"

.PP
Definition at line 56 of file videowidget\&.cpp\&.
.SS "void VideoWidget::mouseDoubleClickEvent (QMouseEvent * event)\fC [override]\fP, \fC [protected]\fP"

.PP
Definition at line 71 of file videowidget\&.cpp\&.
.SS "void VideoWidget::mousePressEvent (QMouseEvent * event)\fC [override]\fP, \fC [protected]\fP"

.PP
Definition at line 77 of file videowidget\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for WheelMonitor from the source code\&.
