.TH "sources/videowidget.cpp" 3 "Sat Jan 5 2019" "Version 1.0.2" "WheelMonitor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sources/videowidget.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'stdafx\&.h'\fP
.br
\fC#include 'videowidget\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for WheelMonitor from the source code\&.
