.TH "ViewSensorImage" 3 "Sat Jan 5 2019" "Version 1.0.2" "WheelMonitor" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ViewSensorImage
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ViewSensorImage\&.h>\fP
.PP
Inherits QDialog\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBViewSensorImage\fP (QWidget *parent=Q_NULLPTR)"
.br
.ti -1c
.RI "\fB~ViewSensorImage\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file ViewSensorImage\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ViewSensorImage::ViewSensorImage (QWidget * parent = \fCQ_NULLPTR\fP)"

.PP
Definition at line 4 of file ViewSensorImage\&.cpp\&.
.SS "ViewSensorImage::~ViewSensorImage ()"

.PP
Definition at line 10 of file ViewSensorImage\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for WheelMonitor from the source code\&.
