ConfigHelper
QString ConfigHelper::configFile
bool ConfigHelper::launchAtLogin
Referenced by read, save.
bool ConfigHelper::startAtLaunch
alias click "start" after launch this app
Referenced by read, save, MainWindow::MainWindow.
bool ConfigHelper::verboseLog
record verbose log
Referenced by read, save.
DevSpec ConfigHelper::device[2][2]
所有的属性值都储存在这里，每次使用时都调用helper类，才能保证设置的生效的实时性。
Referenced by read, save.
QString ConfigHelper::pc2plc_portName
Referenced by read, save, Plc::connect.
double ConfigHelper::matchMaskInnerRatio
匹配时，抠出的内圆半径占车轮的比例
Referenced by read.
double ConfigHelper::matchMaskOuterRatio
匹配时，抠出的外圆半径占车轮的比例
Referenced by read.
ConfigHelper::ConfigHelper(const QString &configuration, QObject *parent=Q_NULLPTR)
construct a confighelper object using specified file
this constructor will auto read() config.ini.
References read.
ConfigHelper::~ConfigHelper()
References save.
void ConfigHelper::read()
read from ini
References GP_COMMON, launchAtLogin, startAtLaunch, verboseLog, pc2plc_portName, matchMaskOuterRatio, matchMaskInnerRatio, GP_DEV, device, GP_CAM, DevSpec::camProfile, CamProfile::camIP, GP_IM, GP_OCR.
Referenced by ConfigHelper.
void ConfigHelper::save()
References GP_COMMON, launchAtLogin, startAtLaunch, verboseLog, pc2plc_portName, GP_DEV, device, GP_CAM, DevSpec::camProfile, GP_IM, GP_OCR.
Referenced by ~ConfigHelper, MainWindow::closeEvent.
void ConfigHelper::takeEffect() const
take the indirect change into effect, including common/launchAtLogin, etc. perhaps use signal, or implement by self.在保存时，向外主动输出（一次性），而不是供其他类（在调用时）查询
void ConfigHelper::effect_launchAtLogin() const