AlarmManager
Plc* AlarmManager::m_plc
MainWindow* AlarmManager::m_mainWindow
int AlarmManager::currentCio100
AlarmManager::AlarmManager(QObject *parent)
AlarmManager::~AlarmManager()
void AlarmManager::bindPLC(Plc *plc)
References hardAlarmToPlc, Plc::sendAlarmToControlCenter, Plc::handleSensorDevice, HandleSensorDevice::wheelFallOff.
void AlarmManager::bindImProc(ImageProcess *imp)
References ImageProcess::wheelNeedHandled.
void AlarmManager::bindMainWindow(MainWindow *mainwindow)
References showSpeed_o, MainWindow::uiShowSpeed_o, showNum_o, MainWindow::uiShowNum_o, showError_o, MainWindow::uiShowError_o, showSpeed_i, MainWindow::uiShowSpeed_i, showNum_i, MainWindow::uiShowNum_i, showError_i, MainWindow::uiShowError_i, showCio100ToUi, MainWindow::uiShowCio100, showAlarmLightToUi, MainWindow::uiShowAlarmLight.
void AlarmManager::bindPlayBack(PlayBackWidget *pb)
References PlayBackWidget::clearAlarm, MainWindow::uiShowAlarmLight, Green.
void AlarmManager::onHardwareAlarm(HardwareAlarmEvent event)
当PLC发出掉轮报警，更新ui界面（DOCK和警报灯），并由PLC向中控发出报警
References Reset, Outer_Warn, Outer_Alarm, Inner_Warn, Inner_Alarm, showCio100ToUi, hardAlarmToPlc, showAlarmLightToUi, Red.
void AlarmManager::showCio100ToUi(int)
掉轮报警信号
中控报警信号（PLC CIO100）在UI中的显示 connect to UI todo
Referenced by bindMainWindow, onHardwareAlarm.
void AlarmManager::hardAlarmToPlc(int)
中控报警信号发送至PLC中进行处理 connect to PLC todo.
Referenced by bindPLC, onHardwareAlarm.
void AlarmManager::showAlarmLightToUi(int)
设置UI界面的报警灯的颜色 connect to UI.
Referenced by bindMainWindow, onHardwareAlarm.
void AlarmManager::showSpeed_i(double)
Referenced by bindMainWindow.
void AlarmManager::showError_i(double)
Referenced by bindMainWindow.
void AlarmManager::showNum_i(QString)
Referenced by bindMainWindow.
void AlarmManager::showSpeed_o(double)
Referenced by bindMainWindow.
void AlarmManager::showError_o(double)
Referenced by bindMainWindow.
void AlarmManager::showNum_o(QString)
Referenced by bindMainWindow.
bool AlarmManager::insertRecord(WheelDbInfo info)
int AlarmManager::getPreCheckstate(QString num)
获取当前序号的车轮前一次检测的结果，如果无，返回正确
void AlarmManager::checkoutWheelToDb(WheelDbInfo info)
根据车轮的警报等级向报警处理类发出信号