ImageProcess
CoreState
车轮定位丢失
const ConfigHelper* ImageProcess::configHelper
HikVideoCapture* ImageProcess::videoCapture
Plc* ImageProcess::plcSerial
int ImageProcess::deviceIndex
const ImProfile* ImageProcess::imProfile
OCR* ImageProcess::ocr
ocr识别的类，只通过start/stop来控制，常开
RobustMatcher* ImageProcess::rMatcher
cv::Mat ImageProcess::srcImg
cv::Mat ImageProcess::undistortedFrame
cv::Mat ImageProcess::frameToShow
cv::Mat ImageProcess::matchResult
QMutex ImageProcess::mutex
std::vector<double> ImageProcess::rtSpeeds
当前车轮的计算速度表
std::vector<double> ImageProcess::refSpeeds
当前车轮的参考速度表，与rtSpeeds大小相同
cv::Mat ImageProcess::wheelFrame_pre
上一帧 车轮外切矩形图像
bool ImageProcess::bInDz
车轮处于detect zone里
bool ImageProcess::checkoutAlready
是否需要checkout，防止重复
int ImageProcess::_MAState
0-进 1-出 2中断 start初始化为1，ss-tri状态切换后重置1（TODO）
int ImageProcess::interrupts
本车轮MA内连续匹配过程中，中断的次数,stop重置为0
bool ImageProcess::bUsrCtrl
ctrl the imageprocecss running state 1 is ON, 0 is OFF
bool ImageProcess::bIsTruckStopped
int ImageProcess::nCore_pre
存本车轮上一次core的返回值，初始化为findfail
double ImageProcess::rtRefSpeed
ImageProcess::ImageProcess(const ConfigHelper *_configHelper, HikVideoCapture *_capture, Plc *_plcSerial, QObject *parent=Q_NULLPTR)
References HikVideoCapture::recordTimeout, onWheelTimeout, Plc::truckSpeedReady, Plc::getTruckSpeed, Plc::handleSensorDevice, HandleSensorDevice::dzIn, onSensorIN, HandleSensorDevice::dzOut, onSensorOUT, frameHandled, HikVideoCapture::frameProcessed, HikVideoCapture::frameCaptured, handleFrame, HikVideoCapture::startRecord, HikVideoCapture::stopRecord.
ImageProcess::~ImageProcess()
cv::Mat ImageProcess::getFrameToShow()
cv::Mat ImageProcess::getMatchResult()
void ImageProcess::start()
void ImageProcess::stop()
cv::Mat ImageProcess::cameraUndistort(cv::Mat src)
void ImageProcess::checkoutWheel()
结算该车轮
QString ImageProcess::genSpeeds(std::vector< double > rt, std::vector< double > ref)
生成写入数据库speeds列的数据
void ImageProcess::clearWheel()
清除当前车轮的相关信息
int ImageProcess::coreImageProcess()
图像处理核心代码，返回CoreStates，输入为scrImg和undistortedFrame.
void ImageProcess::preprocess()
static bool ImageProcess::isInside(cv::Rect rect1, cv::Rect rect2)
判断rect1是否在rect2.
void ImageProcess::_MAIn()
void ImageProcess::_MAOut()
void ImageProcess::frameHandled()
Referenced by ImageProcess, handleFrame.
void ImageProcess::showFrame()
Referenced by handleFrame.
void ImageProcess::showMatch()
Referenced by MatchViewer::bindDev.
void ImageProcess::wheelNeedHandled(WheelDbInfo info)
Referenced by AlarmManager::bindImProc.
void ImageProcess::handleFrame()
处理当前帧，每秒钟3次
References makeFrame4Show, ImProfile::sensorTriggered, frameHandled, showFrame.
Referenced by ImageProcess.
void ImageProcess::makeFrame4Show()
References ImProfile::roiRect.
Referenced by handleFrame.
void ImageProcess::onSensorIN()
完全进入后（进后）
Referenced by ImageProcess.
void ImageProcess::onSensorOUT()
开始退出前（出前）
Referenced by ImageProcess.
void ImageProcess::onWheelTimeout()
Referenced by ImageProcess.
void ImageProcess::onStart()
开始处理
void ImageProcess::onStop()
停止处理，仍保留每帧显示的功能