SpeedIntegrator
Plc* SpeedIntegrator::plc
bool SpeedIntegrator::bUsrCtrl
struct SpeedIntegrator::Ckpt SpeedIntegrator::ckps[4][4]
const int SpeedIntegrator::readSpeedInterval
读取ad的间隔ms
const double SpeedIntegrator::std_L
标准轮距
const double SpeedIntegrator::dist_min
const double SpeedIntegrator::dist_max
SpeedIntegrator::SpeedIntegrator(Plc *plcSerial, QObject *parent=Q_NULLPTR)
SpeedIntegrator::~SpeedIntegrator()
void SpeedIntegrator::start()
开始积分。调用时间：plc初始化后
Referenced by Plc::Plc, Plc::start.
void SpeedIntegrator::stop()
Referenced by Plc::stop.
void SpeedIntegrator::speedIntegrator()
void SpeedIntegrator::onCkpTri(int ckpId)
Referenced by Plc::Plc.
void SpeedIntegrator::expectTriBegin(int ckpId)
Referenced by Plc::Plc.
void SpeedIntegrator::expectTriEnd(int ckpId)
Referenced by Plc::Plc.