CkPt
int CkPt::id
Referenced by Sensor::Sensor.
int CkPt::m_id
Referenced by CkPt.
SensorDevice* CkPt::parentDev
Referenced by CkPt, isEnter.
QString CkPt::name
Referenced by CkPt, isEnter.
bool CkPt::hasTri
Referenced by newWheel.
QList<Sensor*> CkPt::sensors
Referenced by CkPt, newWheel, init.
const QStringList CkPt::names
每个检测点的传感器
Referenced by CkPt, creatAll, indexOf.
CkPt::CkPt(int _id, SensorDevice *parent)
References name, names, m_id, parentDev, SensorDevice::id, sensors, Sensor::createAll.
void CkPt::newWheel()
References sensors, hasTri.
void CkPt::init()
References sensors.
int CkPt::triTiming()
返回触发的时机，如果是进入，则下降沿触发
References isEnter, LevelRecorder::NegativeEdge, LevelRecorder::PositiveEdge.
bool CkPt::isEnter()
返回是否由此检测点进入
References parentDev, SensorDevice::name, name.
Referenced by Sensor::init, triTiming, isLeave.
bool CkPt::isLeave()
返回是否由此检测点离开
References isEnter.
static int CkPt::gid2mid(int gid)
由global id获得局部id.
Referenced by HandleSensorDevice::newCkp, HandleSensorDevice::checkoutCkp.
static int CkPt::indexOf(QString _name)
References names.
Referenced by HandleSensorDevice::io2dev.
QList< CkPt * > CkPt::creatAll(SensorDevice *parent)
一次性创建所有的检测点
References names.
Referenced by SensorDevice::SensorDevice.