Player
QMediaPlayer::State Player::playerState
QMediaPlayer* Player::player
VideoWidget* Player::videoWidget
CustomSlider* Player::slider
QPushButton* Player::playButton
QPushButton* Player::fullScreenButton
QPushButton* Player::openFilePathBtn
QLabel* Player::labelDuration
QString Player::statusInfo
qint64 Player::duration
QString Player::currentFileName
Player::Player(QWidget *parent=nullptr)
References CustomSlider::costomSliderClicked, play, pause.
Player::~Player()
void Player::setUrl(const QUrl &url)
Referenced by PlayBackWidget::clearMedia.
void Player::fullScreenChanged(bool fullScreen)
void Player::play()
Referenced by Player.
void Player::pause()
Referenced by Player.
void Player::durationChanged(qint64 duration)
void Player::positionChanged(qint64 progress)
void Player::seek(int seconds)
void Player::statusChanged(QMediaPlayer::MediaStatus status)
void Player::videoAvailableChanged(bool available)
void Player::setState(QMediaPlayer::State state)
void Player::playClicked()
void Player::openFilePath()
void Player::handleCursor(QMediaPlayer::MediaStatus status)
void Player::updateDurationInfo(qint64 currentInfo)
QMediaPlayer::State Player::state() const