HikVideoCapture
const ConfigHelper* HikVideoCapture::configHelper
int HikVideoCapture::deviceIndex
HWND HikVideoCapture::hPlayWnd
const CamProfile* HikVideoCapture::camProfile
QMutex HikVideoCapture::mutex
bool HikVideoCapture::bIsRecording
timeoutTimer和plc的sensorout会从子线程改变这个量，需要线程保护//原子操作，不用保护
QString HikVideoCapture::videoRelativeFilePath
the fileName of save video.
QTimer* HikVideoCapture::timeoutTimer
录制的超时计时器，停止录制时停止
const int HikVideoCapture::MAX_RECORD_MSEC
录制的超时时长，超过会自动停止录制，并发出timeout的信号
cv::Mat HikVideoCapture::rawImage
const int HikVideoCapture::nHandling_Start
于开始视频流后进行一次初始化
volatile int HikVideoCapture::nHandling
the countdown counter 倒计数器
int HikVideoCapture::nPendingFrame
图像线程处理时，对于本线程来说就是待处理的帧，由于不缓存，只能是0或1. 0 is ready for next cap, 1 must wait for processed.
LONG HikVideoCapture::lUserID
LONG HikVideoCapture::nPort
LONG HikVideoCapture::lRealPlayHandle_SD
for save video
LONG HikVideoCapture::lRealPlayHandle_HD
for process and show
NET_DVR_PREVIEWINFO HikVideoCapture::struPlayInfo_HD
for process and show
NET_DVR_PREVIEWINFO HikVideoCapture::struPlayInfo_SD
for save
HikVideoCapture * HikVideoCapture::pCap0
HikVideoCapture * HikVideoCapture::pCap1
HikVideoCapture::HikVideoCapture(const ConfigHelper *_configHelper, int _deviceIndex, HWND h, QObject *parent=Q_NULLPTR)
References CamProfile::camIP, CamProfile::camUserName, CamProfile::camPassword, CamProfile::camPort, syncCameraTime.
HikVideoCapture::~HikVideoCapture()
References stop.
QString HikVideoCapture::getVideoRelativeFilePath() const
int HikVideoCapture::getDeviceIndex() const
cv::Mat HikVideoCapture::getRawImage() const
void HikVideoCapture::syncCameraTime()
Referenced by HikVideoCapture.
bool HikVideoCapture::start()
bool HikVideoCapture::stop()
References stopRecord.
Referenced by ~HikVideoCapture.
void HikVideoCapture::DecCBFun(char *pBuf, FRAME_INFO *pFrameInfo)
void CALLBACK HikVideoCapture::DecCBFun0(long nPort, char *pBuf, long nSize, FRAME_INFO *pFrameInfo, long nReserved1, long nReserved2)
void CALLBACK HikVideoCapture::DecCBFun1(long nPort, char *pBuf, long nSize, FRAME_INFO *pFrameInfo, long nReserved1, long nReserved2)
void CALLBACK HikVideoCapture::fRealDataCallBack(LONG lRealHandle, DWORD dwDataType, BYTE *pBuffer, DWORD dwBufSize, void *pUser)
实时流回调
void CALLBACK HikVideoCapture::ExceptionCallBack(DWORD dwType, LONG lUserID, LONG lHandle, void *pUser)
void HikVideoCapture::frameCaptured()
a frame is captured, need to be processed
Referenced by ImageProcess::ImageProcess.
void HikVideoCapture::recordTimeout()
record out of time, will auto stop and save video
Referenced by startRecord, ImageProcess::ImageProcess.
void HikVideoCapture::recordON()
now is recording
Referenced by startRecord.
void HikVideoCapture::recordOFF()
now record stopped
Referenced by stopRecord.
void HikVideoCapture::startRecord()
References videoDirPath, stopRecord, recordTimeout, recordON.
Referenced by ImageProcess::ImageProcess.
void HikVideoCapture::stopRecord()
涉及到timeoutTimer，可能跨线程，必须通过sg/sl机制调用
References recordOFF.
Referenced by stop, startRecord, ImageProcess::ImageProcess.
void HikVideoCapture::frameProcessed()
涉及到timeoutTimer，可能跨线程，必须通过sg/sl机制调用
Referenced by ImageProcess::ImageProcess.