Sensor
int Sensor::id
000~111
int Sensor::show_id
标记的位置，1~8
Referenced by Sensor.
int Sensor::m_id
Referenced by Sensor.
CkPt* Sensor::parentCkPt
Referenced by Sensor, init.
QString Sensor::name
Referenced by Sensor.
int Sensor::nTri
Referenced by newWheel.
bool Sensor::expected
记录传感器是否坏掉
Referenced by newWheel.
bool Sensor::broken
记录传感器是否坏掉（周期结束时更新）
LevelRecorder Sensor::sample
记录传感器的采样信息
Referenced by init.
const QStringList Sensor::names
每个检测点的传感器
Referenced by Sensor, createAll, indexOf.
Sensor::Sensor(int _id, CkPt *parent)
References name, names, m_id, parentCkPt, CkPt::id, show_id.
void Sensor::newWheel()
References nTri, expected.
Referenced by init.
void Sensor::init()
References newWheel, parentCkPt, CkPt::isEnter, sample, LevelRecorder::init.
static int Sensor::id_gb2mem(int gid)
由global id获得局部id.
static int Sensor::indexOf(QString _name)
References names.
Referenced by HandleSensorDevice::io2dev.
QList< Sensor * > Sensor::createAll(CkPt *parent)
References names.
Referenced by CkPt::CkPt.