MainWindow
Ui::MainWindowClass MainWindow::ui
ConfigHelper* MainWindow::configHelper
QMutex MainWindow::mutex
bool MainWindow::bIsRunning
QLabel* MainWindow::recLabel_pre[2][2]
QLabel* MainWindow::recLabel_input[2][2]
HikVideoCapture* MainWindow::videoCapture[2][2]
PlayBackWidget* MainWindow::playBackWidget
ImageProcess* MainWindow::imageProcess[2][2]
QThread* MainWindow::imageProcessThread[2][2]
Plc* MainWindow::plc
QThread* MainWindow::plcThread
QFileSystemWatcher* MainWindow::watcher
QThread* MainWindow::dbWatcherThread
AlarmManager* MainWindow::alarmManager
QDataWidgetMapper* MainWindow::alarmMapper
QList<QDockWidget*> MainWindow::m_docks
MainWindow::MainWindow(ConfigHelper *_configHelper, QWidget *parent=Q_NULLPTR)
只有该类可以改变config，因此不用const.
References ConfigHelper::startAtLaunch.
MainWindow::~MainWindow()
void MainWindow::configWindow()
void MainWindow::setupDatabaseWatcher()
建立对数据库文件的监视
void MainWindow::setupDataMapper()
建立数据库与界面的映射关系
bool MainWindow::cleanDir(QString dir, int nDays)
retain nDays save files, include video/match/log and so on, defualt retain for 0 days, which means clean all
void MainWindow::closeEvent(QCloseEvent *event) override
References ConfigHelper::save.
void MainWindow::uiShowCio100(int cio100)
显示Cio100的灯。即中控报警灯，1为亮，0为灭
Referenced by AlarmManager::bindMainWindow.
void MainWindow::uiShowAlarmLight(AlarmColor alarmColor)
References Unkown, Green, Red, Yellow, Gray.
Referenced by AlarmManager::bindMainWindow, AlarmManager::bindPlayBack.
void MainWindow::uiShowSpeed_i(double speed)
Referenced by AlarmManager::bindMainWindow.
void MainWindow::uiShowError_i(double error)
Referenced by AlarmManager::bindMainWindow.
void MainWindow::uiShowNum_i(QString num)
Referenced by AlarmManager::bindMainWindow.
void MainWindow::uiShowSpeed_o(double speed)
Referenced by AlarmManager::bindMainWindow.
void MainWindow::uiShowError_o(double error)
Referenced by AlarmManager::bindMainWindow.
void MainWindow::uiShowNum_o(QString num)
Referenced by AlarmManager::bindMainWindow.
void MainWindow::uiShowRealtimeImage(int deviceIndex)
void MainWindow::uiShowTruckSpeed()
void MainWindow::uiShowCio0(int cio0)
void MainWindow::uiShowSensor(int state, int devId)
更新界面的光电传感器状态
void MainWindow::onRecordON(int deviceIndex)
void MainWindow::onRecordOFF(int deviceIndex)
void MainWindow::execScheduledTasks()
void MainWindow::setupScheduler(int hh, int mm, bool execnow=true, bool everyday=true)
void MainWindow::on_action_Start_triggered()
void MainWindow::on_action_Stop_triggered()
void MainWindow::on_action_Restart_triggered()
void MainWindow::on_action_Property_triggered()
void MainWindow::on_action_Quit_triggered()
void MainWindow::on_action_Show_Log_triggered()
void MainWindow::on_action_Backup_Log_triggered()
void MainWindow::on_action_About_triggered()
void MainWindow::on_action_About_Qt_triggered()
void MainWindow::on_alarmPushButton_clicked()
void MainWindow::showViewSensorImage()
void MainWindow::alarmUi2PLC(AlarmColor alarmcolor)