Identification
Identification::Identification(QObject *parent=Q_NULLPTR)
Identification::~Identification()=default
bool Identification::check()
References getCPUID, getLocalMAC, CPU_ID, LOCAL_MAC.
void Identification::getCPUID(unsigned int CPUInfo[4], unsigned int InfoType)
References getCPUIDEX.
Referenced by check.
void Identification::getCPUIDEX(unsigned int CPUInfo[4], unsigned int InfoType, unsigned int ECXValue)
Referenced by getCPUID.
QString Identification::getLocalMAC()
Referenced by check.