Plc
const int Plc::adInterval
读取ad（车速）的间隔，ms // 不应太频繁，应大于图像处理的时间7/25s，否则无意义
HandleSensorDevice* Plc::handleSensorDevice[2][2]
Referenced by AlarmManager::bindPLC, ImageProcess::ImageProcess, Plc, start.
const ConfigHelper* Plc::configHelper
SpeedIntegrator* Plc::speedIntegrator
QMutex Plc::mutex
QSerialPort* Plc::plcSerialPort
QThread* Plc::refThread
double Plc::truckSpeed
const double Plc::speedCompensationCoeff[2][2]
bool Plc::bUsrCtrl
bool Plc::bConnected
const int Plc::cio0Interval
读取cio0（传感器）的间隔，ms
const int Plc::serialport_timeout
Plc::Plc(const ConfigHelper *_configHelper, QObject *parent=nullptr)
必须传入configure, const成员变量在初始化列表中初始化
References handleSensorDevice, HandleSensorDevice::triInt, SpeedIntegrator::onCkpTri, SpeedIntegrator::expectTriBegin, HandleSensorDevice::newCkp, SpeedIntegrator::expectTriEnd, HandleSensorDevice::checkoutCkp, SpeedIntegrator::start.
Plc::~Plc()
void Plc::start()
usrctrl
References handleSensorDevice, HandleSensorDevice::dev, SensorDevice::init, SpeedIntegrator::start.
void Plc::stop()
usrctrl
References SpeedIntegrator::stop, cio0Update.
void Plc::connect()
连接到PLC，初始化AD041。在plc创建并移到子线程后执行，应在退出程序时断开
通过串口连接到plc
References ConfigHelper::pc2plc_portName, connectError.
double Plc::getTruckSpeed(int devId=0) const
获取台车速度(m/min)，线程安全的
Referenced by ImageProcess::ImageProcess.
void Plc::writePLC(QByteArray plcData)
QByteArray Plc::readPLC(QByteArray plcData)
QByteArray Plc::getFCSCode(QByteArray cmd) const
根据命令码获取FCS码，通常情况下不需要直接调用
QByteArray Plc::getFullCode(QByteArray cmd) const
根据命令码获取完整指令码
QByteArray Plc::genRRCode(int addr, int num) const
返回读取cio所需要的完整指令码
generate a RR command code PC to PLC ask(command) code "@00RR0001(ADDR)0001(No. of words)FCS*\r" except data and end code is hex, the others is BCD. int addr (cio) register address of beginning word to read int num how many words to read
QByteArray Plc::genWRCode(int addr, QByteArray data) const
返回写入cio所需要的完整指令码
generate a WR command code PC to PLC ask(command) code "@00WR0100(ADDR)data(words,hex)FCS*\r" except data and end code is hex, the others is BCD. int addr (cio) register address of beginning word to write QByteArray data how many words to read or the data to write
bool Plc::checkAnsCode(QByteArray ansCode) const
检查应答是否正确
check answer code if it's right. PLC to PC answer(response) code: "@00RR00(endcode,hex)data(words,hex)FCS*\r" "@00WR00(endcode,hex)FCS*\r" except data and end code is hex, the others is BCD. QByteArray
QByteArrayList Plc::getRRData(QByteArray ansCode) const
从应答中提取n个字的数据(hex)
get RR data from response code QByteArrayList hex data list
void Plc::readSensorPeriodically()
void Plc::readSpeedPeriodically()
read truck reference speed from AD module. a cycle includes sending cmd and recv response, costs ~300ms
void Plc::cio0Update(int cio)
Referenced by stop.
void Plc::connectError(int errorId)
Referenced by connect.
void Plc::truckSpeedReady()
Referenced by ImageProcess::ImageProcess.
void Plc::truckSpeedError(int)
台车(中轴)速度信号读取错误 errcode 1: disconnect errcode 2: out of range(4~20ma)
int errorCode
void Plc::sendAlarmToControlCenter(int cio)
向中控发出报警
注意：不会覆盖原有状态
Referenced by AlarmManager::bindPLC.