PlayBackWidget
MySqlTableModel* PlayBackWidget::allModel
tableModel for all record
Referenced by dbChanged.
MySqlTableModel* PlayBackWidget::alarmModel
talbleModel for unchecked record
Referenced by hasAlarm, dbChanged.
QTableView* PlayBackWidget::alarmView
tablseview for unchecked record
Referenced by PlayBackWidget.
QComboBox* PlayBackWidget::selectTableCb
Referenced by PlayBackWidget.
QTableView* PlayBackWidget::allView
tableview for all record
Player* PlayBackWidget::player
QPushButton* PlayBackWidget::checkSelBtn
QPushButton* PlayBackWidget::checkAllBtn
PlayBackWidget::PlayBackWidget(QWidget *parent=Q_NULLPTR)
References selectTableCb, alarmView, clearMedia.
PlayBackWidget::~PlayBackWidget()
bool PlayBackWidget::hasAlarm() const
Returns true if the alarm list is not null;otherwise returns false.
References alarmModel.
Referenced by dbChanged.
void PlayBackWidget::initAlarmTable()
initialize the alarm(unchecked) table view
void PlayBackWidget::initAllTable()
initialize the all-record table view
void PlayBackWidget::clearAlarm()
Referenced by AlarmManager::bindPlayBack, dbChanged.
void PlayBackWidget::clearMedia()
清除媒体信息；应当在失焦时调用
References Player::setUrl.
Referenced by PlayBackWidget.
void PlayBackWidget::dbChanged()
References allModel, alarmModel, hasAlarm, clearAlarm.
void PlayBackWidget::readVideoPath(QModelIndex) const
void PlayBackWidget::setSelectedChecked()
void PlayBackWidget::setAllChecked()