HandleSensorDevice
SensorDevice* HandleSensorDevice::dev
Referenced by io2dev, checkTri, newCkp, checkoutCkp, Plc::start.
int HandleSensorDevice::devId
HandleSensorDevice::HandleSensorDevice(int _devId, QObject *parent)
HandleSensorDevice::~HandleSensorDevice()
void HandleSensorDevice::input(int io)
输入一个新的io信号
References io2dev, checkTri.
void HandleSensorDevice::io2dev(int io)
将输入的io信号压入devs中
References dev, SensorDevice::ckpts, CkPt::indexOf, Sensor::indexOf.
Referenced by input.
void HandleSensorDevice::checkTri()
用读取的cio数据检测是否满足触发条件（上升沿/下降沿）
References dev, SensorDevice::ckpts.
Referenced by input.
void HandleSensorDevice::newCkp(int ckpId)
expect begin时，开始一个新的ckp
References CkPt::gid2mid, dev, SensorDevice::ckpts.
Referenced by Plc::Plc.
void HandleSensorDevice::checkoutCkp(int ckpId)
在expect end时，结算ckp。注意：此ckpId为global id.
References CkPt::gid2mid, dev, SensorDevice::ckpts, dzIn, dzOut.
Referenced by Plc::Plc.
void HandleSensorDevice::checkoutDev()
void HandleSensorDevice::emitDzSignal(int ckpId)
void HandleSensorDevice::updateBrokenSensor()
void HandleSensorDevice::updateGoodSensor()
int HandleSensorDevice::getBreaks()
int HandleSensorDevice::getBrokens()
int HandleSensorDevice::getExpects()
void HandleSensorDevice::updateSensorToUi()
void HandleSensorDevice::dzIn()
Referenced by checkoutCkp, ImageProcess::ImageProcess.
void HandleSensorDevice::dzOut()
Referenced by checkoutCkp, ImageProcess::ImageProcess.
void HandleSensorDevice::triInt(int ckpId)
至积分器,global ckpid.
Referenced by Plc::Plc.
void HandleSensorDevice::wheelFallOff(int pos)
pos:-1前一个;0当前
Referenced by AlarmManager::bindPLC.
void HandleSensorDevice::sensorUpdate(int)